module.exports = [
[
    //0 MAIN PAGE BOTTOM PAGE LINKS
    //Company
    {selector: '@companyOverview', url: 'https://www.hamiltoncompany.com/about-us'},
    {selector: '@companyCareers', url: 'https://www.hamiltoncompany.com/careers'},
    {selector: '@companyNews', url: 'https://www.hamiltoncompany.com/news'},
    {selector: '@companyPress', url: 'https://www.hamiltoncompany.com/press-releases'},
    {selector: '@companyEvents', url: 'https://www.hamiltoncompany.com/events'},
    {selector: '@companyCertifications', url: 'https://www.hamiltoncompany.com/certifications'},
    //Support
    {selector: '@supportALH', url: 'https://www.hamiltoncompany.com/automated-liquid-handling/support'},
    {selector: '@supportASM', url: 'https://www.hamiltoncompany.com/automated-sample-management/support'},
    {selector: '@supportLaboratory', url: 'https://www.hamiltoncompany.com/laboratory-products/support'},
    {selector: '@supportProcessAnalytics', url: 'https://www.hamiltoncompany.com/process-analytics/support'},
    {selector: '@supportOEM', url: 'https://www.hamiltoncompany.com/oem/support'},
    //Legal
    {selector: '@legalPrivacy', url: 'https://www.hamiltoncompany.com/privacy-policy'},
    {selector: '@legalConditions', url: 'https://www.hamiltoncompany.com/general-terms-and-conditions'},
    {selector: '@legalUse', url: 'https://www.hamiltoncompany.com/terms-of-use'},
    {selector: '@legalTrademarks', url: 'https://www.hamiltoncompany.com/trademarks'},
],
[
    //1 SEARCHES
    {search: 'automation', result: 'automation'},
    {search: 'STARlet', result: 'STARlet',},
    {search: '235658', result: 'Piercing Conductive Filter Tips'},
    {search: 'HHS', result: 'Hamilton Heater Shaker'},
    {search: 'syringe', result: 'Syringe'},
    {search: 'sensor', result: 'sensor'},
],
[
    //2 SOCIAL MEDIA LINKS
    {link: '@alhFacebook', url: 'https://www.facebook.com/HamiltonRobotic/'},
    {link: '@alhtwitter', url: 'https://twitter.com/HamiltonRobotic'},
    {link: '@alhlinkedin', url: 'https://www.linkedin.com/showcase/hamilton-robotics/'},
    {link: '@alhyoutube', url: 'https://www.youtube.com/user/HamiltonRobotics'},
    {link: '@asmtwitter', url: 'https://twitter.com/HamiltonCompany'},
    {link: '@asmlinkedin', url: 'https://www.linkedin.com/company/hamilton-storage-technologies/'},
    {link: '@asmyoutube', url: 'https://www.youtube.com/user/HamiltonStorage'},
    {link: '@lablinkedin', url: 'https://www.linkedin.com/showcase/hamilton-laboratory-products/'},
    {link: '@labyoutube', url: 'https://www.youtube.com/user/HamiltonRobotics'},
    {link: '@proclinkedin', url: 'https://www.linkedin.com/showcase/hamilton-process-analytics/'},
    {link: '@procyoutube', url: 'https://www.youtube.com/user/HamiltonBonaduzAG'},
    {link: '@oemlinkedin', url: 'https://www.linkedin.com/showcase/hamilton-oem-components/'},
    {link: '@oemyoutube', url: 'https://www.youtube.com/channel/UCWaFECeSoG9wnjTUDfJ9e9g'}
],
[
    //3 DROP DOWNS
    //Links that are commented out have a bug where the page won't fully load (the tab continues to spin). This causes the automation to break.
    {category: '@automationDropdown', link: '@autoLiquidHandling', url: 'https://www.hamiltoncompany.com/automated-liquid-handling'},
    {category: '@automationDropdown', link: '@autoLHApplications', url: 'https://www.hamiltoncompany.com/automation/applications'},
    {category: '@automationDropdown', link: '@autoLHPlatforms', url: 'https://www.hamiltoncompany.com/automated-liquid-handling/platforms'},
    {category: '@automationDropdown', link: '@autoLHAssays', url: 'https://www.hamiltoncompany.com/automated-liquid-handling/assay-ready-workstations'},
    {category: '@automationDropdown', link: '@autoLHSmallDevices', url: 'https://www.hamiltoncompany.com/automated-liquid-handling/small-devices'},
    {category: '@automationDropdown', link: '@autoLHConsumables', url: 'https://www.hamiltoncompany.com/automated-liquid-handling/consumables'},
    {category: '@automationDropdown', link: '@autoSampleManagement', url: 'https://www.hamiltoncompany.com/automated-sample-management'},
    {category: '@automationDropdown', link: '@autoSMPlatforms', url: 'https://www.hamiltoncompany.com/automated-sample-management/platforms/products'},
    {category: '@automationDropdown', link: '@autoSMBenchtops', url: 'https://www.hamiltoncompany.com/automated-sample-management/benchtop-devices'},
    {category: '@automationDropdown', link: '@autoSMConsumables', url: 'https://www.hamiltoncompany.com/automated-sample-management/consumables'},
    {category: '@automationDropdown', link: '@autoSMApplications', url: 'https://www.hamiltoncompany.com/automation/applications'},
    {category: '@automationDropdown', link: '@autoAll', url: 'https://www.hamiltoncompany.com/automation'},
    {category: '@laboratoryDropdown', link: '@labProducts', url: 'https://www.hamiltoncompany.com/laboratory-products'},
    {category: '@laboratoryDropdown', link: '@labProdSyringes', url: 'https://www.hamiltoncompany.com/laboratory-products/syringes'},
    {category: '@laboratoryDropdown', link: '@labProdNeedles', url: 'https://www.hamiltoncompany.com/laboratory-products/needles'},
    {category: '@laboratoryDropdown', link: '@labProdColumns', url: 'https://www.hamiltoncompany.com/laboratory-products/hplc-columns'},
    {category: '@laboratoryDropdown', link: '@labProdDispensers', url: 'https://www.hamiltoncompany.com/laboratory-products/microlab-600'},
    {category: '@laboratoryDropdown', link: '@labProdPipettes', url: 'https://www.hamiltoncompany.com/laboratory-products/pipettes-and-pipettors'},
    // {category: '@laboratoryDropdown', link: '@labProdPH', url: 'https://www.hamiltoncompany.com/laboratory-products/laboratory-sensors'},
    {category: '@laboratoryDropdown', link: '@labProdValves', url: 'https://www.hamiltoncompany.com/laboratory-products/valves-fittings-tubing'},
    {category: '@laboratoryDropdown', link: '@labProdSepta', url: 'https://www.hamiltoncompany.com/laboratory-products/gc-septa'},
    {category: '@laboratoryDropdown', link: '@labHighlights', url: 'https://www.hamiltoncompany.com/laboratory-products'},
    {category: '@laboratoryDropdown', link: '@labHighSyringe', url: 'https://www.hamiltoncompany.com/laboratory-products/syringes/general-syringes/products'},
    {category: '@laboratoryDropdown', link: '@labHighNeedle', url: 'https://www.hamiltoncompany.com/laboratory-products/needles/products'},
    {category: '@laboratoryDropdown', link: '@labHighHPLC', url: 'https://www.hamiltoncompany.com/laboratory-products/hplc-applications'},
    {category: '@laboratoryDropdown', link: '@labHighSales', url: 'https://www.hamiltoncompany.com/laboratory-products/support'},
    {category: '@laboratoryDropdown', link: '@labHighKnowledge', url: 'https://www.hamiltoncompany.com/laboratory-products/support/documents'},
    {category: '@laboratoryDropdown', link: '@labAll', url: 'https://www.hamiltoncompany.com/laboratory-products'},
    // {category: '@processDropdown', link: '@processProducts', url: 'https://www.hamiltoncompany.com/process-analytics'},
    // {category: '@processDropdown', link: '@processProdpH', url: 'https://www.hamiltoncompany.com/process-analytics/sensors/ph-and-orp-probes'},
    // {category: '@processDropdown', link: '@processProdDisOxygen', url: 'https://www.hamiltoncompany.com/process-analytics/sensors/dissolved-oxygen'},
    // {category: '@processDropdown', link: '@processProdConduct', url: 'https://www.hamiltoncompany.com/process-analytics/sensors/conductivity'},
    // {category: '@processDropdown', link: '@processProdCellDens', url: 'https://www.hamiltoncompany.com/process-analytics/sensors/cell-density-sensors'},
    // {category: '@processDropdown', link: '@processProdAccessories', url: 'https://www.hamiltoncompany.com/process-analytics/accessories'},
    // {category: '@processDropdown', link: '@processHighlights', url: 'https://www.hamiltoncompany.com/process-analytics'},
    // {category: '@processDropdown', link: '@processHighArc', url: 'https://www.hamiltoncompany.com/process-analytics'},
    // {category: '@processDropdown', link: '@processHighPortDisOx', url: 'https://www.hamiltoncompany.com/process-analytics/accessories/communication-and-controllers/arc-software-and-accessories'},
    // {category: '@processDropdown', link: '@processHighBrowse', url: 'https://www.hamiltoncompany.com/process-analytics/applications'},
    {category: '@processDropdown', link: '@processHighKnowledge', url: 'https://www.hamiltoncompany.com/process-analytics/support/documents'},
    {category: '@processDropdown', link: '@processHighQuality', url: 'https://www.hamiltoncompany.com/process-analytics/certificates'},
    // {category: '@processDropdown', link: '@processAll', url: 'https://www.hamiltoncompany.com/process-analytics'},
    {category: '@oemDropdown', link: '@oemSystems', url: 'https://www.hamiltoncompany.com/oem/oem-systems'},
    {category: '@oemDropdown', link: '@oemSysGetStarted', url: 'https://www.hamiltoncompany.com/oem/oem-systems/oem-getting-started'},
    {category: '@oemDropdown', link: '@oemSysProcess', url: 'https://www.hamiltoncompany.com/oem/oem-systems/oem-process'},
    {category: '@oemDropdown', link: '@oemComponents', url: 'https://www.hamiltoncompany.com/oem/oem-components'},
    // {category: '@oemDropdown', link: '@oemCompPipette', url: 'https://www.hamiltoncompany.com/oem/oem-components/pipette-channels'},
    // {category: '@oemDropdown', link: '@oemCompPumps', url: 'https://www.hamiltoncompany.com/oem/oem-components/syringe-pumps'},
    {category: '@oemDropdown', link: '@oemCompValve', url: 'https://www.hamiltoncompany.com/oem/oem-components/valve-positioners'},
    // {category: '@oemDropdown', link: '@oemCompInstSyr', url: 'https://www.hamiltoncompany.com/oem/oem-components/instrument-syringes'},
    // {category: '@oemDropdown', link: '@oemCompSensors', url: 'https://www.hamiltoncompany.com/oem/process-sensors-for-oem'},
    // {category: '@oemDropdown', link: '@oemAll', url: 'https://www.hamiltoncompany.com/oem'},
],
[
    //4  News by year
    {year: 'all', url: 'https://www.hamiltoncompany.com/news'},
    {year: '2018', url: 'https://www.hamiltoncompany.com/news?year=2018'},
    {year: '2016', url: 'https://www.hamiltoncompany.com/news?year=2016'},
    {year: '2015', url: 'https://www.hamiltoncompany.com/news?year=2015'},
    {year: '2014', url: 'https://www.hamiltoncompany.com/news?year=2014'},
    {year: '2013', url: 'https://www.hamiltoncompany.com/news?year=2013'},
    {year: '2012', url: 'https://www.hamiltoncompany.com/news?year=2012'},
    {year: '2011', url: 'https://www.hamiltoncompany.com/news?year=2011'},
    {year: '2010', url: 'https://www.hamiltoncompany.com/news?year=2010'},
    {year: '2009', url: 'https://www.hamiltoncompany.com/news?year=2009'}
],
[
    //5 Press releases by year
    {year: 'all', url: 'https://www.hamiltoncompany.com/press-releases'},
    {year: '2019', url: 'https://www.hamiltoncompany.com/press-releases?year=2019'},
    {year: '2018', url: 'https://www.hamiltoncompany.com/press-releases?year=2018'},
    {year: '2017', url: 'https://www.hamiltoncompany.com/press-releases?year=2017'},
    {year: '2016', url: 'https://www.hamiltoncompany.com/press-releases?year=2016'},
    {year: '2015', url: 'https://www.hamiltoncompany.com/press-releases?year=2015'},
    {year: '2014', url: 'https://www.hamiltoncompany.com/press-releases?year=2014'}
],
[
    //6 CONTACT NUMBERS
    {country: 'Germany', region: '//div[5]/div/select/option[4]', code: '49 '},
    {country: 'Chile', region: 'NA', code: '56 '},
    {country: 'China', region: 'NA', code: '86 '},
    {country: 'Italy', region: 'NA', code: '39 '},
    {country: 'Peru', region: 'NA', code: '51 '},
    {country: 'United Kingdom', region: '//div[7]/div/select/option[112]', code: '44 '},
],
]